language: ruby

cache:
  - bundler
  - apt
  - npm
  
env:
  global:
    secure: "cqBfVO7XKbE8MtDHGnB9O4UnMebwxNM5VtzKqFTRcHv1hTO1g/Z1d2fMkqOeLooIwtNAoqKxAvEg/PeGNKoPBKLBKI5suD24mIp2iQ9tOkyp80c4XtBvZBaios4M5cBGCpwML0I8dCj96ECyiuu6FrmwHelWQPQjmzmNC9V/mNQ="

matrix:
  fast_finish: true
  
branches:
  only:
    - master


  
script:
  - chmod u+x *.sh . -R
  #- ./test0.sh
  #- ./test.sh
  - sudo -E su $LOGNAME -c ./steps.sh
  - bash -c ./finish.sh
